version: '3.6'

services:
  iris_api:
    image: iris_api
    container_name: iris_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ops/release/Dockerfile
    command: uvicorn iris_api.app.main:app --host 0.0.0.0 --port 8000
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 8000
      MONGODB_DATABASE: iris
      MONGODB_USERNAME: iris_user
      MONGODB_HOSTNAME: mongodb
      MONGODB_PASSWORD: iris_password
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - appdata:/iris_api
    
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb 
    restart: unless-stopped 
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
      MONGO_INITDB_DATABASE: iris
      MONGODB_DATA_DIR: /data/db
      MONGOODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db 
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local